week0/sangjin
juhwanHeo/study-k8s pull request #11
Opened 2024-07-17 12:37 UTC by sangjin0521

week0 과제 제출입니다

2024-07-17 14:48 UTC, juhwanHeo requested changes
한 가지 수정 사항이 있습니다.
- 과제 제출 시 file path는 `week주차/이름`을 base로 해주세요.

container 내부 통신 시 compose 파일만 보고 해당 container의 port를 알 수 있는 방법은 좋은 것 같습니다.

2024-07-17 14:48 UTC, juhwanHeo commented on board/docker-compose.yml
해당 파일 내용을 `week0/sangjin/nginx/nginx.conf`파일과 같은 위치에 작성하여 주시고, 해당 `board/docker-compose.yml` 파일은 원복해 주세요
- Ex) `week0/sangjin/docker-compose.yml`

2024-07-17 14:48 UTC, juhwanHeo commented on board/docker-compose.yml
> +      - "8080"
컨테이너 간에 통신에서 host pc에 port를 노출 시키지 않고, 
docker-compose.yml만 보고 해당 컨테이너(board)에서 사용중인 포트를 알려줄 수 있는 좋은 방법 인것 같습니다.

2024-07-18 14:01 UTC, juhwanHeo requested changes
`commit suggestion` 해 주시면 됩니다.

2024-07-18 14:01 UTC, juhwanHeo commented on board/docker-compose.yml
> +    image: studyKubernatis/board:1.0
```suggestion
    image: k8s-study/board:1.1
```

2024-07-18 23:13 UTC, juwonlee-dev requested changes
PR 제목과 내용이 적절하게 수정되어야합니다.

2024-07-18 23:26 UTC, juhwanHeo approved these changes

2024-07-22 12:10 UTC, juwonlee-dev requested changes

2024-07-22 12:10 UTC, juwonlee-dev commented on week0/sangjin/docker-compose.yml
> +      - /c/sjKimProject/studyKubernatis/week0/sangjin/nginx/nginx.conf:/etc/nginx/nginx.conf
절대경로를 사용하면 다른 환경에서도 동일한 경로를 설정해야하므로 작업PC에 따른 변경사항이 없도록 수정하는 것이 좋습니다

2024-08-08 07:58 UTC, juwonlee-dev approved these changes
해결된 사항은 reslove를 누른 후 리뷰를 요청해주세요.

2024-08-08 08:16 UTC, merged