Week 0 juwonlee
juhwanHeo/study-k8s pull request #12
Opened 2024-07-17 13:30 UTC by juwonlee-dev

작업내용
- board 이미지 기본설정 추가
- 0주차 과제 수행
  - nginx 이미지 추가
  - nginx 설정파일 볼륨 마운트 추가
  - nginx reverse proxy 설정(nginx:80 -> board:8080)

2024-07-17 14:52 UTC, juhwanHeo requested changes
`board/docker-compose.yml` 파일은 이번 과제에 관련된 파일이 아닙니다.

2024-07-17 14:52 UTC, juhwanHeo commented on board/docker-compose.yml
> +    image: k8s-study/board:1.0
해당 파일은 이번 과제 내용에 포함되지 않는 파일입니다. 기존 설정으로 올려주세요

```suggestion
    image: k8s-study/board:1.1
```

2024-07-21 04:39 UTC, juhwanHeo approved these changes

2024-08-08 07:58 UTC, siyoungwoo approved these changes

2024-08-08 07:58 UTC, merged