Week0 / ujin
juhwanHeo/study-k8s pull request #14
Opened 2024-07-19 17:10 UTC by Mik-WJ

add nginx and nginx proxy setting

2024-07-20 02:58 UTC, juhwanHeo requested changes
upstream 식별자 관련 수정사항이 있습니다.

2024-07-20 02:58 UTC, juhwanHeo commented on week0/ujin/nginx/default.conf
> +    upstream board_ {
upstream 식별자에 `_` postfix 보다는 -api postfix는 어떨까요?

```suggestion
    upstream board-api {
```

2024-07-20 02:58 UTC, juhwanHeo commented on week0/ujin/nginx/default.conf
> +            proxy_pass http://board_;
```suggestion
            proxy_pass http://board-api;
```

2024-07-22 12:00 UTC, juwonlee-dev approved these changes

2024-07-22 13:42 UTC, juhwanHeo approved these changes

2024-07-22 13:42 UTC, merged