Week0/sjeong 과제1 제
juhwanHeo/study-k8s pull request #19
Opened 2024-07-24 00:21 UTC by COVER-SJ

과제1 제출
: Docker compose(docker-compose.yml)를 통해 Reverse Proxy 구성

./SJeong 폴더안에 파일 2개 신규생성
docker-compose.yml
nginx.conf

2024-07-24 08:34 UTC, juhwanHeo approved these changes
과제를 전부 수행했을 경우에는 아래 그림과 같이 Reviewers 탭의 설정 버튼을 눌러서
- 그 주차의 발표자
- juhwanHeo (필수)
- juwonlee-dev (필수)
최소 2명 이상의 리뷰어를 등록해주셔야 합니다.

![image](https://github.com/user-attachments/assets/48173c86-270e-474a-951d-349c5eada323)

만약 작업중인 PR일 경우 제목에 WIP prefix를 달아 주세요.

2024-07-24 08:34 UTC, juhwanHeo commented on board/week0/SJeong/docker-compose.yml
> +      - "8080"
board application에서 내부 네트워크(docker private 망)에서 사용하는 포트를 파일에서 확인 하는 방법은 좋은 것 같습니다.

2024-07-24 09:16 UTC, juhwanHeo requested changes

2024-07-24 09:16 UTC, juhwanHeo commented on board/week0/SJeong/docker-compose.yml
> +    #  - "8080"
이전 방법(`expose`)이 맞습니다.
제가 코멘트한 내용은 
`expose`를 통해서 컨테이너 통신에 필요한 port 정보를 노출 시키는 것이 좋은 방법인것 같아 남겨 놓은 내용입니다.

--- 
`posts`는 host와 container 간의 통신을 위한 필드이고,
  - host <-> container

`expose`는 container 내부 통신에서 다른 컨테이너에서 접근할 수 있도록 하는 목적으로 사용합니다.
  - container <-> container

2024-08-19 12:14 UTC, COVER-SJ commented on board/week0/SJeong/docker-compose.yml
> +    #  - "8080"
앗 제가 잘못이해했습니다.
외부 호스트도 허용하도록 하는 게 좋겠다는 의미로 받아들여서 고쳤었습니다.
다시 수정해서 올렸습니다!

2024-08-19 12:16 UTC, COVER-SJ commented
* ports와 expose의 차이에 대해 간략하게 설명해놓은 블로그가 있어서 참고용으로 첨부합니다.

https://growd.tistory.com/77

2024-08-20 09:10 UTC, juhwanHeo approved these changes

2024-08-21 04:42 UTC, juhwanHeo approved these changes

2024-08-21 12:06 UTC, juwonlee-dev approved these changes

2024-08-21 12:06 UTC, merged