week1/woo
juhwanHeo/study-k8s pull request #21
Opened 2024-08-08 12:34 UTC by siyoungwoo

- woo-namespace / woo-nginx-pod yaml 파일 생성

2024-08-09 23:28 UTC, juwonlee-dev requested changes
과제에 명시된 실행결과를 캡쳐하여 PR에 첨부해주세요.

2024-08-10 01:33 UTC, juhwanHeo requested changes
수정 요청사항
- 다음주차부터 과제 branch 이름을 지켜주세요.
```
과제를 진행하실 때, branch 이름은
`과제의주차/이름`
main <- week1/siyoung 으로 PR 올려주세요

현재는 
main <- week0/sangjin
입니다.
```
- 과제 2, 3의 결과 캡처 파일을 올려주세요.

2024-08-11 06:11 UTC, siyoungwoo commented
![KakaoTalk_20240808_172102692](https://github.com/user-attachments/assets/98a08ce0-9082-4c4f-b1bf-6b02444744c7)
![KakaoTalk_20240808_213244717](https://github.com/user-attachments/assets/d9ed2820-8d88-4e96-8b26-b36a8a5aa1fb)

2024-08-12 13:18 UTC, juwonlee-dev commented
브랜치를 적절하게 수정하시기 바랍니다.
week0이 아닌 week1입니다.

2024-08-13 02:13 UTC, closed without merging