week1 과제제출
juhwanHeo/study-k8s pull request #23
Opened 2024-08-10 12:20 UTC by sangjin0521

- week1 과제제출

2번 과제제출입니다
<img width="377" alt="week1_김상진_과제2" src="https://github.com/user-attachments/assets/738ecc4c-2898-414f-beee-76c23b5461e5">

3번 과제제출입니다
<img width="722" alt="week1_김상진_과제3" src="https://github.com/user-attachments/assets/5b33af1f-127a-41f5-aae3-402ee0352582">

2024-08-10 12:46 UTC, juwonlee-dev requested changes
yaml 파일을 올려주세요.

2024-08-10 16:20 UTC, juwonlee-dev requested changes
Github에서 스크린샷은 PR 내용을 작성할 때, 이미지를 복사/붙여넣기해도 자동으로 들어갑니다.   
별도의 파일로 커밋하는 것보다는, 마크다운 문법을 맞춰서 작성하는게 좋을 것 같습니다.

2024-08-10 16:20 UTC, juwonlee-dev commented on week1/김상진/sangjin-namespace.yaml
> +  creationTimestamp: null
creationTimestamp는 해당 namespace가 생성된 시간을 의미하는데, 필수값이 아니므로 사용하지 않는다면 해당 구문을 삭제해도 됩니다.

2024-08-10 16:20 UTC, juwonlee-dev commented on week1/김상진/sangjin-nginx-pod.yaml
> +
불필요한 개행입니다.
```suggestion
```

2024-08-12 13:17 UTC, juwonlee-dev approved these changes

2024-08-12 13:41 UTC, juhwanHeo requested changes
수정사항이 있습니다.
1. `yaml` 파일 형식과 안맞는 표현식이 있습니다.
  - `Commit suggestion` 버튼으로 바로 반영됩니다. 확인해 주시고 버튼 누룬후 Re-Review 부탁드립니다.

2024-08-12 13:41 UTC, juhwanHeo commented on week1/김상진/sangjin-namespace.yaml
> +metadata
yaml 파일 형식에 안 맞습니다. 아래와 같이 수정해 주세요.
(suggestion commit 하기 버튼 누루시면 바로 아래와 같이 반영됩니다.)
```suggestion
metadata:
```

2024-08-18 07:49 UTC, juwonlee-dev approved these changes

2024-08-18 08:20 UTC, juhwanHeo approved these changes

2024-08-18 08:20 UTC, merged