Week2 / Multi Container Pod / sooJung
juhwanHeo/study-k8s pull request #35
Opened 2024-08-24 10:03 UTC by COVER-SJ

: 2주차 과제 Multi Container Pod 생성

* multi-container-pod의 ip
![image](https://github.com/user-attachments/assets/85cd0670-9938-4dc9-b0b5-a005a0a29cef)

2024-08-24 14:19 UTC, juhwanHeo requested changes
리뷰 내용 수정 후 

Master Node에서 
http://localhost/board 출력 결과를 포함시켜주시길 바랍니다.

2024-08-24 14:19 UTC, juhwanHeo commented on week2/sooJung/multi-container.yaml
> +        - containerPort: 80
해당 container port는 8080입니다.

2024-08-24 14:19 UTC, juhwanHeo commented on week2/sooJung/multi-container.yaml
> +      image: nginx:latest
Nginx를 통해서 board container를 통신하도록 reverse proxy를 구성해 주세요.

2024-08-24 21:43 UTC, juwonlee-dev requested changes
리뷰어를 올바르게 등록하시기 바랍니다.
리뷰어는 총 3명을 지정해야합니다. @juhwanHeo @juwonlee-dev 에 해당 과제 주차에 대한 강의 발표자를 포함하여 3명을 리뷰어로 지정합니다.

2024-08-28 09:56 UTC, juwonlee-dev requested changes
과제 내용을 다시 확인해주세요.
http://localhost/board 요청 결과를 PR본문에 포함시켜야 합니다.

2024-11-29 07:32 UTC, closed without merging