2024. 08. 20 -1
juhwanHeo/study-k8s pull request #39
Opened 2024-08-25 04:40 UTC by siyoungwoo

- multi-pod를 사용한 reverse-proxy 구성

![image](https://github.com/user-attachments/assets/16530a03-ab2c-40a8-ba7c-e82aeb4443ed)

![image](https://github.com/user-attachments/assets/2c7c17a6-7794-4afd-b30e-caab3302eb49)

curl을 사용한 접근이 되지 않아, 포트포워딩을 사용해 결과를 출력했습니다.
방화벽 설정을 시도해보았지만, 에러발생으로 해당 방법을 사용했습니다.

2024-08-25 04:48 UTC, juwonlee-dev requested changes
PR 제목을 올바르게 변경해주세요.

2024-08-26 09:30 UTC, juhwanHeo approved these changes

2024-08-26 14:28 UTC, Mik-WJ approved these changes

2024-08-28 09:54 UTC, juwonlee-dev approved these changes

2024-08-28 09:54 UTC, merged