Week3/ livenessProb, static, resource limited Pod / Sangjin
juhwanHeo/study-k8s pull request #45
Opened 2024-09-20 05:04 UTC by sangjin0521

issue: https://github.com/juhwanHeo/study-k8s/issues/38
과제2)
<img width="907" alt="static-board" src="https://github.com/user-attachments/assets/63f085f8-9a08-4831-9324-bb893a88d044">

2024-09-20 08:50 UTC, juwonlee-dev requested changes
파일 경로가 올바르지 않습니다. 과제 내용을 정독하시길 바랍니다.

2024-09-20 09:07 UTC, juhwanHeo approved these changes

2024-09-21 10:03 UTC, LSHgy approved these changes

2024-09-21 16:10 UTC, juwonlee-dev approved these changes

2024-09-21 16:11 UTC, merged