Week4 / Controller / siyoung
juhwanHeo/study-k8s pull request #50
Opened 2024-10-07 08:29 UTC by siyoungwoo

![rollingUpdate Describe](https://github.com/user-attachments/assets/0d7cb4f6-cc4d-483f-a5f5-136492691bb4)
과제2-1) describe

![rollingUpdate 결과사진](https://github.com/user-attachments/assets/3516896f-bd5a-4c32-b77e-8f260203d4cc)
과제2-2) result

2024-10-08 08:28 UTC, juhwanHeo requested changes
제가 이슈에 자세한 설명을 못 쓴거 같습니다.

예시를 추가하였습니다. 확인 후 수정 부탁드립니다.

2024-10-08 08:28 UTC, juhwanHeo commented on week4/siyoung/cronjob-board.yaml
> +  schedule: "3 * * * *"
0시 3분, 1시 3분, 2시 3분, ... 에 실행되는 표현식입니다.
3, 6, 9, 12, 15, ... 3 * n 에 실행 되도록 수정해 주세요.

2024-10-13 04:22 UTC, juwonlee-dev approved these changes

2024-10-20 06:55 UTC, juhwanHeo approved these changes

2024-10-21 01:52 UTC, sangjin0521 approved these changes

2024-10-24 06:32 UTC, merged