Week5/Service/siyoung
juhwanHeo/study-k8s pull request #56
Opened 2024-10-22 11:40 UTC by siyoungwoo

과제1) CrusterIP
![clusterIP](https://github.com/user-attachments/assets/3ed014d2-353b-4e77-a8ea-852975ae4b14)

과제2) NodePort
![nodePort](https://github.com/user-attachments/assets/3148ee80-7735-40c5-b930-03c11802ed6b)

과제3) Loadbalancer
![loadbalancer](https://github.com/user-attachments/assets/f6019f0b-ae96-41b5-8a19-ac03d4669ad8)

과제4) ExternalName
![externalname describe svc](https://github.com/user-attachments/assets/924b4462-8745-4f92-9e0f-c446300f92c9)
![externalname curl](https://github.com/user-attachments/assets/8d96f1f6-a63c-4f4a-82ab-f79f16224e2b)

2024-10-24 06:33 UTC, juwonlee-dev approved these changes

2024-10-25 22:00 UTC, juwonlee-dev requested changes
week4는 본 과제와는 무관한 내용입니다.

2024-10-25 22:00 UTC, juwonlee-dev commented on week5/siyoung/loadbalancer-svc-board.yaml
> +      targetPort: 8080
형식에 맞지 않습니다. 들여쓰기를 확인해주세요.

2024-10-25 22:00 UTC, juwonlee-dev commented on week5/siyoung/nodeport-svc-board.yaml
> +      nodePort: 31111
형식에 맞지 않습니다. 들여쓰기를 확인해주세요.

2024-10-25 22:00 UTC, juwonlee-dev commented on week4/siyoung/board-replication.yaml
> +          image: gjwnghks99/board:1.0.0
형식에 맞지 않습니다. 들여쓰기를 확인해주세요.

2024-10-25 22:00 UTC, juwonlee-dev commented on week4/siyoung/cronjob-board.yaml
> +              image: gjwnghks99/board:1.0.0
형식에 맞지 않습니다. 들여쓰기를 확인해주세요.

2024-10-25 22:00 UTC, juwonlee-dev commented on week4/siyoung/rolling-update-replication.yaml
> +          image: gjwnghks99/board:1.0.1
형식에 맞지 않습니다. 들여쓰기를 확인해주세요.

2024-11-13 15:32 UTC, juhwanHeo approved these changes

2024-11-15 21:30 UTC, juwonlee-dev approved these changes

2024-11-15 21:30 UTC, merged