WIP) Week5 / Service / lshan
juhwanHeo/study-k8s pull request #57
Opened 2024-10-25 09:07 UTC by LSHgy

## Issue #54

### Task1
![image](https://github.com/user-attachments/assets/d9b1a68e-fb2c-4fe9-952e-9d6b1157d6e9)

### Task2

2024-10-26 20:03 UTC, juwonlee-dev requested changes

2024-10-26 20:03 UTC, juwonlee-dev commented on week5/yiseoul/cluster-ip-svc-board.yaml
> +    - protocol: TCP
형식에 맞지 않습니다. 들여쓰기를 확인해주세요.

2024-10-26 20:03 UTC, juwonlee-dev commented on week5/yiseoul/deployment.yaml
> +        - name: board
형식에 맞지 않습니다. 들여쓰기를 확인해주세요.

2024-10-26 20:03 UTC, juwonlee-dev commented on week5/yiseoul/deployment.yaml
> +            - containerPort: 8080
형식에 맞지 않습니다. 들여쓰기를 확인해주세요.

2024-10-26 20:03 UTC, juwonlee-dev commented on week5/yiseoul/loadbalancer-svc-board.yaml
> +    - protocol: TCP
형식에 맞지 않습니다. 들여쓰기를 확인해주세요.

2024-10-26 20:03 UTC, juwonlee-dev commented on week5/yiseoul/nodeport-svc-board.yaml
> +    - protocol: TCP
형식에 맞지 않습니다. 들여쓰기를 확인해주세요.

2024-11-05 14:43 UTC, LSHgy commented on week5/yiseoul/cluster-ip-svc-board.yaml
> +    - protocol: TCP
들여쓰기가 되어있어도 문법 상 문제가 없습니다.

2024-11-05 14:43 UTC, LSHgy commented on week5/yiseoul/loadbalancer-svc-board.yaml
> +    - protocol: TCP
들여쓰기가 되어있어도 문법 상 문제가 없습니다.

2024-11-05 14:43 UTC, LSHgy commented on week5/yiseoul/deployment.yaml
> +            - containerPort: 8080
들여쓰기가 되어있어도 문법 상 문제가 없습니다.

2024-11-05 14:43 UTC, LSHgy commented on week5/yiseoul/nodeport-svc-board.yaml
> +    - protocol: TCP
들여쓰기가 되어있어도 문법 상 문제가 없습니다.

2024-11-13 15:31 UTC, juhwanHeo approved these changes

2024-11-15 21:30 UTC, juwonlee-dev approved these changes

2024-11-15 21:30 UTC, merged