Week5/ Service / juhwan
juhwanHeo/study-k8s pull request #59
Opened 2024-10-26 15:21 UTC by juhwanHeo

issue: #54 

### 과제1)
![image](https://github.com/user-attachments/assets/a40df686-8964-4182-8fd4-097fb98029d2)

### 과제2)
![image](https://github.com/user-attachments/assets/3fdbc901-5e27-4e06-8c7f-20045b211e5c)

### 과제3)
![image](https://github.com/user-attachments/assets/2bafba83-4e19-4396-a84c-105af7bf8900)

### 과제4)
- describe
![image](https://github.com/user-attachments/assets/eacb45ba-f115-4d53-b20e-6428f73a54ec)

- curl
![image](https://github.com/user-attachments/assets/c51934b9-3067-47ee-82b9-ebf94c676ae3)

2024-10-26 20:05 UTC, juwonlee-dev requested changes

2024-10-26 20:05 UTC, juwonlee-dev commented on week5/juhwan/cluster-ip-svc-board.yaml
> +    - protocol: TCP
형식에 맞지 않습니다. 들여쓰기를 확인해주세요.

2024-10-26 20:05 UTC, juwonlee-dev commented on week5/juhwan/loadbalancer-svc-board.yaml
> +    - protocol: TCP
형식에 맞지 않습니다. 들여쓰기를 확인해주세요.

2024-10-26 20:05 UTC, juwonlee-dev commented on week5/juhwan/nodeport-svc-board.yaml
> +    - protocol: TCP
형식에 맞지 않습니다. 들여쓰기를 확인해주세요.

2024-11-15 21:29 UTC, juwonlee-dev approved these changes

2024-12-16 01:25 UTC, siyoungwoo approved these changes

2024-12-16 01:25 UTC, merged