Week5/ Service / daejun
juhwanHeo/study-k8s pull request #60
Opened 2024-10-26 19:24 UTC by joon5380

과제 1번
![image](https://github.com/user-attachments/assets/b0de76c0-0cf6-4ed1-bec2-634cb5a28f5b)

과제 2번
![image](https://github.com/user-attachments/assets/b66e90bc-c531-4a19-b89e-f27fc91a7092)

과제 3번
![image](https://github.com/user-attachments/assets/1fb05887-9e98-4afa-89e0-90c61ae092ac)

과제 4번
![image](https://github.com/user-attachments/assets/52720e9d-eb2f-4690-92b7-cce5b2961ebe)
![image](https://github.com/user-attachments/assets/5d8cca2e-e9a1-4e70-8a67-8eb9f8cc34a3)

2024-10-26 20:07 UTC, juwonlee-dev requested changes

2024-10-26 20:07 UTC, juwonlee-dev commented on week5/daejun/cluster-ip-svc-board.yaml
> +    - protocol: TCP
형식에 맞지 않습니다. 들여쓰기를 확인해주세요.

2024-10-26 20:07 UTC, juwonlee-dev commented on week5/daejun/loadbalancer-svc-board.yaml
> +    - protocol: TCP
형식에 맞지 않습니다. 들여쓰기를 확인해주세요.

2024-10-26 20:07 UTC, juwonlee-dev commented on week5/daejun/nodeport-svc-board.yaml
> +    - protocol: TCP
형식에 맞지 않습니다. 들여쓰기를 확인해주세요.

2024-11-13 15:30 UTC, juhwanHeo approved these changes

2024-11-15 21:29 UTC, juwonlee-dev approved these changes

2024-11-15 21:29 UTC, merged