\Week6 / Ingress, Label / siyoung
juhwanHeo/study-k8s pull request #63
Opened 2024-11-14 06:41 UTC by siyoungwoo

과제 1)
![image](https://github.com/user-attachments/assets/eb862de6-1508-4875-b419-227b0c8b97fc)

과제 2)
![image](https://github.com/user-attachments/assets/6d1ff8c0-2820-4ed8-8cd4-330e35726d68)

2024-11-16 07:01 UTC, juwonlee-dev requested changes

2024-11-16 07:01 UTC, juwonlee-dev commented on week6/siyoung/board-replication.yaml
> +  replicas: 1
과제에서 주어진 조건과 다릅니다.

2024-11-16 07:01 UTC, juwonlee-dev commented on week6/siyoung/hello-pod.yaml
> +kind: Deployment
해당 파일명이 용도와 목적에 부적절합니다.

2024-11-16 07:01 UTC, juwonlee-dev commented on week6/siyoung/hello-pod.yaml
> +        - image: gjwnghks99/board:1.0.0
board와 hello를 각각 다른 버전의 board 이미지를 사용하도록 Deployment를 구성해야 합니다.

2024-11-16 13:46 UTC, juhwanHeo requested changes
제가 [issue](https://github.com/juhwanHeo/study-k8s/issues/61)에
`gjwnghks99/board:1.0.0` 으로 표기했었네요.. 죄송합니다.
24.11.16 22:46:00 쯤 수정하였습니다.

`gjwnghks99/hello:1.0.0` 으로 설정후 다시 올려주세요!

2024-11-16 13:46 UTC, juhwanHeo commented on week6/siyoung/hello-deployment.yaml
> +        - image: gjwnghks99/board:1.0.0
해당 이미지를 
`gjwnghks99/hello:1.0.0` 으로 설정해야 합니다.

2024-11-17 05:34 UTC, juhwanHeo approved these changes

2024-12-11 07:01 UTC, juwonlee-dev approved these changes

2024-12-11 07:11 UTC, merged