WIP) Week6 / Ingress, Label / juwonlee
juhwanHeo/study-k8s pull request #64
Opened 2024-11-15 21:23 UTC by juwonlee-dev

issue: #61 

과제1)
![image](https://github.com/user-attachments/assets/a0540abc-6ed6-4240-a10c-4b28d1172ec1)

과제2)

2024-11-16 06:51 UTC, LSHgy approved these changes

2024-11-16 06:52 UTC, LSHgy approved these changes

2024-11-16 13:42 UTC, juhwanHeo requested changes
host 속성을 주석처리한 이유가 따로 있다면 설명해 주시고, rereview 요청 부탁드립니다.
아니라면, 해당 내용 수정후 rereview 해주세용!

2024-11-16 13:42 UTC, juhwanHeo commented on week6/juwonlee/board-ingress.yaml
> +    #- host: juwon.ingress.com
해당 host 속성을 주석처리한 이유가 있을 까요??

2024-11-16 13:53 UTC, juwonlee-dev commented
네트워크 문제로 인해 외부 또는 호스트PC에서 VirtualBox의 가상 네트워크에 원활하게 접근할 수 없는 환경에서 테스트를 진행하기 위해 별도로 호스트를 지정하지 않고 테스트를 진행했습니다.  
Ingress의 host를 지정하지 않으면 *로 설정하여 모든 host에서 Ingress가 구분하여 처리하도록 설정이 가능합니다.

2024-11-17 05:32 UTC, juhwanHeo approved these changes

2024-11-17 05:32 UTC, merged