WIP) Week6 / Ingress, Label / yisoul
juhwanHeo/study-k8s pull request #65
Opened 2024-11-16 07:14 UTC by LSHgy

## Issue #64

### 과제 1

### 과제 2

2024-11-16 15:20 UTC, juwonlee-dev requested changes
PR 내용에 부적절한 링크가 있습니다.

2024-11-16 15:25 UTC, LSHgy commented
PR Issue 번호 수정했습니다!

2024-11-16 15:26 UTC, juwonlee-dev approved these changes

2024-11-17 05:33 UTC, juhwanHeo approved these changes

2024-11-17 05:33 UTC, merged